/**
 * validation-report.mjs — turn a verify.mjs JSON log into docs/VALIDATION.md.
 *
 *   node tools/validation-report.mjs runs-verify.jsonl > docs/VALIDATION.md
 *
 * Every number in the report comes from the log; nothing is typed in by hand.
 */
import fs from 'fs';

const file = process.argv[2];
if (!file) { console.error('usage: node tools/validation-report.mjs <verify.jsonl>'); process.exit(1); }
const rows = fs.readFileSync(file, 'utf8').trim().split('\n').map((l) => JSON.parse(l));
const VENUES = ['Meteora DLMM', 'Meteora DAMM v2', 'Raydium CLMM', 'Raydium CP', 'Raydium v4', 'Whirlpool', 'Pump.fun Amm'];
const fmt = (x) => (x === null || x === undefined || Number.isNaN(x) ? '—' : x.toFixed(4));
const dates = rows.map((r) => r.clock).filter(Boolean);
const day = dates.length ? new Date(Math.min(...dates) * 1000).toISOString().slice(0, 10) : '?';

const out = [];
out.push('# Validation against mainnet', '');
out.push('Generated by `tools/validation-report.mjs` from a `tools/verify.mjs` run on ' + day + '.', '');
out.push('**Method.** For each pool, in both directions and at three sizes, the quoter prices the swap.',
  'Then the real swap instruction is built for an address that holds the input token and simulated on mainnet.',
  'Nothing is signed or sent. The amount the output token account actually received is compared with the quote, to the unit.',
  'Every account the quote read is then re-read. A row whose state changed before the simulation ran is',
  'counted as **moved** and excluded from the exactness figures, because the chain priced different state than the quote did.', '');

out.push('## Summary', '');
out.push('| Venue | Pools | Simulated | State unchanged | **Exact** | Worst \\|bps\\| (unchanged) | Refused |');
out.push('|---|---:|---:|---:|---:|---:|---:|');
let tSim = 0, tStill = 0, tExact = 0, tRef = 0, tPools = 0;
for (const v of VENUES) {
  const r = rows.filter((x) => x.venue === v);
  if (!r.length) continue;
  const pools = new Set(r.map((x) => x.pool)).size;
  const sim = r.filter((x) => x.chain !== undefined);
  const still = sim.filter((x) => !x.stateMoved);
  const exact = still.filter((x) => x.exact);
  const worst = still.reduce((m, x) => Math.max(m, Math.abs(x.bps)), 0);
  const ref = r.filter((x) => x.verdict === 'refused').length;
  tSim += sim.length; tStill += still.length; tExact += exact.length; tRef += ref; tPools += pools;
  out.push('| ' + v + ' | ' + pools + ' | ' + sim.length + ' | ' + still.length + ' | **' + exact.length + ' / ' + still.length
    + '** | ' + fmt(worst) + ' | ' + ref + ' |');
}
out.push('| **All** | ' + tPools + ' | ' + tSim + ' | ' + tStill + ' | **' + tExact + ' / ' + tStill + '** | | ' + tRef + ' |', '');

const dyn = rows.filter((x) => x.bpsNoDyn !== null && x.bpsNoDyn !== undefined && !x.stateMoved);
if (dyn.length) {
  out.push('## Volatility fees: what a static-fee quote gets wrong', '');
  out.push('Raydium CLMM (`dynamic_fee_info`) and Orca Whirlpool (the adaptive-fee Oracle account) add a volatility-dependent',
    'fee on top of the pool\'s base rate. The same quote with that component switched off (`dynamicFees: false`) would',
    'miss the chain by this much. That is the error a quoter that reads only the base rate makes on these pools.', '');
  out.push('| Venue | Pool | Direction | Amount in | With volatility fee (bps) | Base rate only (bps) |');
  out.push('|---|---|---|---:|---:|---:|');
  for (const x of dyn) {
    out.push('| ' + x.venue + ' | `' + x.pool.slice(0, 8) + '…` | ' + x.label + ' | ' + x.amountIn + ' | ' + fmt(x.bps) + ' | ' + fmt(x.bpsNoDyn) + ' |');
  }
  out.push('');
}

const moved = rows.filter((x) => x.chain !== undefined && x.stateMoved);
if (moved.length) {
  out.push('## Rows where state moved', '');
  out.push('These pools traded between the quote and the simulation, so the two priced different state. They are listed so the',
    'exclusion can be checked, not hidden.', '');
  out.push('| Venue | Pool | Direction | Quoted | Chain | bps |');
  out.push('|---|---|---|---:|---:|---:|');
  for (const x of moved) out.push('| ' + x.venue + ' | `' + x.pool.slice(0, 8) + '…` | ' + x.label + ' | ' + x.quoted + ' | ' + x.chain + ' | ' + fmt(x.bps) + ' |');
  out.push('');
}

const refused = rows.filter((x) => x.verdict !== 'EXACT' && x.verdict !== 'moved' && x.verdict !== 'OFF');
if (refused.length) {
  out.push('## Refusals and rows not simulated', '');
  out.push('The quoter refuses rather than approximate. These are its reasons, as returned:', '');
  out.push('| Venue | Pool | Direction | Amount in | Outcome |');
  out.push('|---|---|---|---:|---|');
  for (const x of refused) out.push('| ' + x.venue + ' | `' + x.pool.slice(0, 8) + '…` | ' + x.label + ' | ' + x.amountIn + ' | ' + x.verdict + ': ' + String(x.reason ?? '').replace(/\|/g, '/') + ' |');
  out.push('');
}

const off = rows.filter((x) => x.verdict === 'OFF');
out.push('## Mismatches on unchanged state', '');
out.push(off.length ? 'These are open issues:' : 'None in this run.', '');
for (const x of off) out.push('- ' + x.venue + ' `' + x.pool + '` ' + x.label + ' ' + x.amountIn + ': quoted ' + x.quoted + ', chain ' + x.chain + ' (' + fmt(x.bps) + ' bps)');
console.log(out.join('\n'));
